### ISSUE TITLE
TypeDB Studio crashes each time I click on database drop down

### ISSUE THREAD

**Issue by tomassabat** [vaticle/typedb-studio#560]
Please replace every line in curly brackets ( { like this } ) with appropriate answers, and remove this line.

## Description
TypeDB Studio crashes each time I click on database drop down

## Environment

TypeDB version: TypeDB 2.9.0
OS of TypeDB server: Mac OS 12.1
Studio version: Master commit 34ca25a
OS of Studio: Mac OS 12.1

## Reproducible Steps

Steps to create the smallest reproducible scenario:

Not quite sure how to fully reproduce this, but this is what led to the crash:
1. I deleted a database, then created a new one with the same name
2. Then I clicked on database drop down, and TypeDB now crashes each time i click on it

Error below: 

```
Title: You should not call runAsyncCommand nested in each other
Trace: java.lang.AssertionError: You should not call runAsyncCommand nested in each other
	at com.vaticle.typedb.studio.state.connection.ClientState.runAsyncCommand(ClientState.kt:126)
	at com.vaticle.typedb.studio.state.connection.ClientState.refreshDatabaseList(ClientState.kt:176)
	at com.vaticle.typedb.studio.view.connection.DatabaseDialog$DatabaseDropdown$1.invoke(DatabaseDialog.kt:178)
	at com.vaticle.typedb.studio.view.connection.DatabaseDialog$DatabaseDropdown$1.invoke(DatabaseDialog.kt:175)
	at com.vaticle.typedb.studio.view.material.Form$Dropdown$DropdownState.toggle(Form.kt:817)
	at com.vaticle.typedb.studio.view.material.Form$Dropdown$2$5$1.invoke(Form.kt:848)
	at com.vaticle.typedb.studio.view.material.Form$Dropdown$2$5$1.invoke(Form.kt:848)
	at com.vaticle.typedb.studio.view.material.Form$BoxButton$1$2.invoke(Form.kt:752)
	at com.vaticle.typedb.studio.view.material.Form$BoxButton$1$2.invoke(Form.kt:752)
	at androidx.compose.foundation.ClickableKt$clickable$4$gesture$1$2.invoke-k-4lQ0M(Clickable.kt:153)
	at androidx.compose.foundation.ClickableKt$clickable$4$gesture$1$2.invoke(Clickable.kt:142)
	at androidx.compose.foundation.gestures.TapGestureDetectorKt$detectTapAndPress$2$1$1.invokeSuspend(TapGestureDetector.kt:225)
	at (Coroutine boundary.()
	at androidx.compose.foundation.gestures.TapGestureDetectorKt$detectTapAndPress$2$1.invokeSuspend(TapGestureDetector.kt:211)
	at androidx.compose.foundation.gestures.TapGestureDetectorKt$detectTapAndPress$2.invokeSuspend(TapGestureDetector.kt:209)
	at androidx.compose.foundation.gestures.ForEachGestureKt.forEachGesture(ForEachGesture.kt:41)
	at androidx.compose.foundation.ClickableKt$clickable$4$gesture$1.invokeSuspend(Clickable.kt:142)
	at androidx.compose.ui.input.pointer.SuspendingPointerInputFilterKt$pointerInput$4$2$1.invokeSuspend(SuspendingPointerInputFilter.kt:274)
Caused by: java.lang.AssertionError: You should not call runAsyncCommand nested in each other
	at com.vaticle.typedb.studio.state.connection.ClientState.runAsyncCommand(ClientState.kt:126)
	at com.vaticle.typedb.studio.state.connection.ClientState.refreshDatabaseList(ClientState.kt:176)
	at com.vaticle.typedb.studio.view.connection.DatabaseDialog$DatabaseDropdown$1.invoke(DatabaseDialog.kt:178)
	at com.vaticle.typedb.studio.view.connection.DatabaseDialog$DatabaseDropdown$1.invoke(DatabaseDialog.kt:175)
	at com.vaticle.typedb.studio.view.material.Form$Dropdown$DropdownState.toggle(Form.kt:817)
	at com.vaticle.typedb.studio.view.material.Form$Dropdown$2$5$1.invoke(Form.kt:848)
	at com.vaticle.typedb.studio.view.material.Form$Dropdown$2$5$1.invoke(Form.kt:848)
	at com.vaticle.typedb.studio.view.material.Form$BoxButton$1$2.invoke(Form.kt:752)
	at com.vaticle.typedb.studio.view.material.Form$BoxButton$1$2.invoke(Form.kt:752)
	at androidx.compose.foundation.ClickableKt$clickable$4$gesture$1$2.invoke-k-4lQ0M(Clickable.kt:153)
	at androidx.compose.foundation.ClickableKt$clickable$4$gesture$1$2.invoke(Clickable.kt:142)
	at androidx.compose.foundation.gestures.TapGestureDetectorKt$detectTapAndPress$2$1$1.invokeSuspend(TapGestureDetector.kt:225)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTaskKt.resume(DispatchedTask.kt:178)
	at kotlinx.coroutines.DispatchedTaskKt.dispatch(DispatchedTask.kt:166)
	at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:397)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:431)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl$default(CancellableContinuationImpl.kt:420)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeWith(CancellableContinuationImpl.kt:328)
	at androidx.compose.ui.input.pointer.SuspendingPointerInputFilter$PointerEventHandlerCoroutine.offerPointerEvent(SuspendingPointerInputFilter.kt:529)
	at androidx.compose.ui.input.pointer.SuspendingPointerInputFilter.dispatchPointerEvent(SuspendingPointerInputFilter.kt:422)
	at androidx.compose.ui.input.pointer.SuspendingPointerInputFilter.onPointerEvent-H0pRuoY(SuspendingPointerInputFilter.kt:435)
	at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(HitPathTracker.kt:285)
	at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(HitPathTracker.kt:272)
	at androidx.compose.ui.input.pointer.NodeParent.dispatchMainEventPass(HitPathTracker.kt:152)
	at androidx.compose.ui.input.pointer.HitPathTracker.dispatchChanges(HitPathTracker.kt:89)
	at androidx.compose.ui.input.pointer.PointerInputEventProcessor.process-BIzXfog(PointerInputEventProcessor.kt:80)
	at androidx.compose.ui.platform.SkiaBasedOwner.processPointerInput-gBdvCQM$ui(SkiaBasedOwner.skiko.kt:343)
	at androidx.compose.ui.platform.SkiaBasedOwner.processPointerInput-gBdvCQM$ui$default(SkiaBasedOwner.skiko.kt:341)
	at androidx.compose.ui.ComposeScene.onMouseReleased(ComposeScene.skiko.kt:451)
	at androidx.compose.ui.ComposeScene.sendPointerEvent-Kr8mkKM(ComposeScene.skiko.kt:427)
	at androidx.compose.ui.ComposeScene.sendPointerEvent-Kr8mkKM$default(ComposeScene.skiko.kt:397)
	at androidx.compose.ui.awt.ComposeLayer_desktopKt.onMouseEvent(ComposeLayer.desktop.kt:420)
	at androidx.compose.ui.awt.ComposeLayer_desktopKt.access$onMouseEvent(ComposeLayer.desktop.kt:1)
	at androidx.compose.ui.awt.ComposeLayer$onMouseEvent$1.invoke(ComposeLayer.desktop.kt:278)
	at androidx.compose.ui.awt.ComposeLayer$onMouseEvent$1.invoke(ComposeLayer.desktop.kt:274)
	at androidx.compose.ui.awt.ComposeLayer.catchExceptions(ComposeLayer.desktop.kt:89)
	at androidx.compose.ui.awt.ComposeLayer.onMouseEvent(ComposeLayer.desktop.kt:274)
	at androidx.compose.ui.awt.ComposeLayer.access$onMouseEvent(ComposeLayer.desktop.kt:70)
	at androidx.compose.ui.awt.ComposeLayer$3.mouseReleased(ComposeLayer.desktop.kt:255)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6632)
	at java.desktop/java.awt.Component.processEvent(Component.java:6397)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5008)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4840)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by haikalpribadi** [comment]
Solved in https://github.com/vaticle/typedb-studio/commit/16a80e5edf67a3c3e62bc57dec04fc30652eef67
