### ISSUE TITLE
[SRV30] Invalid Server Operation: The request message was not recognised.

### ISSUE THREAD

**Issue by stevehcox** [vaticle/typedb-studio#567]
## Description

Having made a connection to the server, studio crashes immediately upon selecting a database. Have deleted and re-installed application with same effect.  ERROR: [SRV30] Invalid Server Operation: The request message was not recognised.

## Environment

1. TypeDB version:  2.8.1
2. OS of TypeDB server: Mac OS 12.4, 
3. Studio version: 2.10.0-alpha-7
4. OS of Studio: Mac OS 12.4
5. Other environment details: 

## Reproducible Steps

Steps to create the smallest reproducible scenario:

1. Open Studio
2. Select Server (successful)
3. Select database from dropdown
4. Error: [SRV30] Invalid Server Operation: The request message was not recognised.

## Expected Output

{ Please describe what you expected to happen. }

## Actual Output

Error: [SRV30] Invalid Server Operation: The request message was not recognised (see log below)

## Additional information

com.vaticle.typedb.client.common.exception.TypeDBClientException: [SRV30] Invalid Server Operation: The request message was not recognised.

Please check server logs for the stack trace.
	at com.vaticle.typedb.client.common.exception.TypeDBClientException.of(TypeDBClientException.java:57)
	at com.vaticle.typedb.client.stream.ResponseCollector$Queue.take(ResponseCollector.java:75)
	at com.vaticle.typedb.client.stream.ResponsePartIterator.fetchAndCheck(ResponsePartIterator.java:56)
	at com.vaticle.typedb.client.stream.ResponsePartIterator.hasNext(ResponsePartIterator.java:86)
	at java.base/java.util.Spliterators$IteratorSpliterator.tryAdvance(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline.findAny(Unknown Source)
	at com.vaticle.typedb.studio.state.schema.SchemaManager.reloadEntries(SchemaManager.kt:93)
	at com.vaticle.typedb.studio.view.material.Navigator$ItemState.reloadEntries$view_material_material(Navigator.kt:188)
	at com.vaticle.typedb.studio.view.material.Navigator$ItemState.expand(Navigator.kt:179)
	at com.vaticle.typedb.studio.view.material.Navigator$ItemState.expand$view_material_material(Navigator.kt:173)
	at com.vaticle.typedb.studio.view.material.Navigator$NavigatorState$initialiseContainer$1.invokeSuspend(Navigator.kt:255)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at androidx.compose.ui.platform.FlushCoroutineDispatcher$dispatch$2$1.invoke(CoroutineDispatchers.skiko.kt:51)
	at androidx.compose.ui.platform.FlushCoroutineDispatcher$dispatch$2$1.invoke(CoroutineDispatchers.skiko.kt:46)
	at androidx.compose.ui.platform.FlushCoroutineDispatcher.performRun(CoroutineDispatchers.skiko.kt:78)
	at androidx.compose.ui.platform.FlushCoroutineDispatcher.access$performRun(CoroutineDispatchers.skiko.kt:29)
	at androidx.compose.ui.platform.FlushCoroutineDispatcher$dispatch$2.invokeSuspend(CoroutineDispatchers.skiko.kt:46)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)
Caused by: io.grpc.StatusRuntimeException: INTERNAL: [SRV30] Invalid Server Operation: The request message was not recognised.

Please check server logs for the stack trace.
	at io.grpc.Status.asRuntimeException(Status.java:535)
	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:479)
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:562)
	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:70)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:743)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:722)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

**Comment by alexjpwalker** [comment]
@stevehcox : This isn't a particularly user-friendly error message, but it's caused by a version mismatch.

TypeDB Studio 2.10.0-alpha-7 is compatible with TypeDB 2.10.0 and above. Attempting to use it with a lower TypeDB version will generate this error.

**Comment by alexjpwalker** [comment]
I've just updated the [release notes](https://github.com/vaticle/typedb-studio/releases/tag/2.10.0-alpha-7) to state the TypeDB version requirements.

**Comment by stevehcox** [comment]
OK, thanks Alex.  I hadn’t noticed the new TypeDB version, so have updated. S

Steve Cox

[A picture containing text, sign, vector graphics  Description automatically generated]

[Logo, company name  Description automatically generated]
Direct:  +44 (0) 20 7924 2345  |  Mobile: +44 (0) 7920027145  |  ***@***.******@***.***>

Important notice:

This message is for the named recipient(s) only. It may contain confidential, proprietary or legally privileged information. No confidentiality is waived or lost by any mis-transmission. If you have received this message in error please immediately notify the sender, delete it and all copies of it from your system and destroy any hard copies. If you are not the intended recipient you must not use, disclose, distribute, print or copy any part of this message directly or indirectly. Internet communications are not secure and subject to possible data corruption, either accidentally or on purpose, and may contain viruses.
At RAIR.AI we are committed to protecting your privacy. This policy applies when we are acting as a controller of personal data, i.e. where we have determined the purposes and means of the processing of that personal data.  If you are a Customer or Supplier of RAIR Health Limited, or an employee of the same, please refer to https://rair.ai/customer-supplier-notice for an important notice regarding your rights as a data subject.

RAIR Health Limited is registered in England: No 10039808, 20 Dents Road, London, SW11 6JA


From: Alex Walker ***@***.***>
Date: Friday, 10 June 2022 at 09:55
To: vaticle/typedb-studio ***@***.***>
Cc: Steve Cox ***@***.***>, Mention ***@***.***>
Subject: Re: [vaticle/typedb-studio] [SRV30] Invalid Server Operation: The request message was not recognised. (Issue #567)

@stevehcox<https://github.com/stevehcox> : This isn't a particularly user-friendly error message, but it's caused by a version mismatch.

TypeDB Studio 2.10.0-alpha-7 is compatible with TypeDB 2.10.0 and above. Attempting to use it with a lower TypeDB version will generate this error.

**Comment by stevehcox** [comment]
Hi Alex - I've updated to 2.10.0 (and confirmed that is what I'm running) but same message.

**Comment by alexjpwalker** [comment]
OK, in that case it's something strange!

Could you possibly take a screencast [screen recording], ideally showing both the running TypeDB server in a terminal window, as well as the TypeDB Studio window as you open it, connect, and select a DB?

**Comment by stevehcox** [comment]
Sure – I’ve sent you a dropbox link


Steve Cox

[A picture containing text, sign, vector graphics  Description automatically generated]

[Logo, company name  Description automatically generated]
Direct:  +44 (0) 20 7924 2345  |  Mobile: +44 (0) 7920027145  |  ***@***.******@***.***>

Important notice:

This message is for the named recipient(s) only. It may contain confidential, proprietary or legally privileged information. No confidentiality is waived or lost by any mis-transmission. If you have received this message in error please immediately notify the sender, delete it and all copies of it from your system and destroy any hard copies. If you are not the intended recipient you must not use, disclose, distribute, print or copy any part of this message directly or indirectly. Internet communications are not secure and subject to possible data corruption, either accidentally or on purpose, and may contain viruses.
At RAIR.AI we are committed to protecting your privacy. This policy applies when we are acting as a controller of personal data, i.e. where we have determined the purposes and means of the processing of that personal data.  If you are a Customer or Supplier of RAIR Health Limited, or an employee of the same, please refer to https://rair.ai/customer-supplier-notice for an important notice regarding your rights as a data subject.

RAIR Health Limited is registered in England: No 10039808, 20 Dents Road, London, SW11 6JA


From: Alex Walker ***@***.***>
Date: Friday, 10 June 2022 at 12:56
To: vaticle/typedb-studio ***@***.***>
Cc: Steve Cox ***@***.***>, Mention ***@***.***>
Subject: Re: [vaticle/typedb-studio] [SRV30] Invalid Server Operation: The request message was not recognised. (Issue #567)

OK, in that case it's something strange!

Could you possibly take a screencast [screen recording], ideally showing both the running TypeDB server in a terminal window, as well as the TypeDB Studio window as you open it, connect, and select a DB?

**Comment by alexjpwalker** [comment]
Hi @stevehcox ,

Thanks - I've taken a look at the recording. It looks like you're starting the TypeDB server on your local machine (with address `0.0.0.0:1729`, aka `localhost:1729`, but then entering a different IP address into the "Address" field in TypeDB Studio. The Address field should also read `0.0.0.0:1729`, or `localhost:1729`.

**Comment by stevehcox** [comment]
Gotcha, well spotted, thanks Alex.

Steve Cox


From: Alex Walker ***@***.***>
Date: Friday, 10 June 2022 at 15:31
To: vaticle/typedb-studio ***@***.***>
Cc: Steve Cox ***@***.***>, Mention ***@***.***>
Subject: Re: [vaticle/typedb-studio] [SRV30] Invalid Server Operation: The request message was not recognised. (Issue #567)

Hi @stevehcox<https://github.com/stevehcox> ,

Thanks - I've taken a look at the recording. It looks like you're starting the TypeDB server on your local machine (with address 0.0.0.0:1729, aka localhost:1729, but then entering a different IP address into the "Address" field in TypeDB Studio. The Address field should also read 0.0.0.0:1729, or localhost:1729.

**Comment by alexjpwalker** [comment]
Great! I'll mark this issue as resolved.
