### ISSUE TITLE
Text editor crashes when an open file is edited by another program

### ISSUE THREAD

**Issue by izmalk** [vaticle/typedb-studio#667]
## Description

TypeDB Studio crashed.
![Снимок экрана 2022-11-24 в 14 57 29](https://user-images.githubusercontent.com/48120135/203781239-a39eced3-26ff-4d23-89bf-e9029b90401e.png)

## Environment

1. TypeDB version: 2.13 
![Снимок экрана 2022-11-24 в 13 38 05](https://user-images.githubusercontent.com/48120135/203783075-ecffa45d-03d1-476e-a65c-4de28bca2c53.png)

3. OS of TypeDB server: MacOS 12.6.1
![Снимок экрана 2022-11-24 в 15 20 50](https://user-images.githubusercontent.com/48120135/203783260-20c20ab1-b6db-4e48-9875-023b78aefc1a.png)

5. Studio version: 2.11
![Снимок экрана 2022-11-24 в 13 37 55](https://user-images.githubusercontent.com/48120135/203783147-1fddad68-5f65-4e0a-bff5-f84a0227c2d7.png)

6. OS of Studio: MacOS 12.6.1 (see above)

8. Other environment details: -

## Reproducible Steps

Steps to create the smallest reproducible scenario:

Can't reproduce it. But that's what was going on:

1. Open schema.tql in Studio
2. While the Studio is on the screen go to IntelliJ IDEA and work there with the schema.tql file. 
3. Suddenly get crash window from the Studio (see above).

Here is what it looked like (more or less, recreated after the crash).

![Снимок экрана 2022-11-24 в 15 04 20](https://user-images.githubusercontent.com/48120135/203782362-644f31ce-2a27-4303-8e0a-c3c396069f52.png)

## Expected Output

Do not Crash. Keep updating the file. 
Maybe not spam so much with the notification popups (see example below).
![Снимок экрана 2022-11-24 в 15 18 40](https://user-images.githubusercontent.com/48120135/203782832-969bf01b-5821-4610-b25c-86535c688663.png)

## Actual Output

Crashed suddenly. Didn't even pay attention to it mostly.

## Additional information

```
Title: offset(23) is out of bounds [0, 21]
Trace: java.lang.IllegalArgumentException: offset(23) is out of bounds [0, 21]
	at androidx.compose.ui.text.MultiParagraph.requireIndexInRangeInclusiveEnd(MultiParagraph.kt:593)
	at androidx.compose.ui.text.MultiParagraph.getCursorRect(MultiParagraph.kt:442)
	at androidx.compose.ui.text.TextLayoutResult.getCursorRect(TextLayoutResult.kt:390)
	at com.vaticle.typedb.studio.framework.editor.TextEditor.Selection-WKfPSdo(TextEditor.kt:427)
	at com.vaticle.typedb.studio.framework.editor.TextEditor.TextLine-AGcomas(TextEditor.kt:401)
	at com.vaticle.typedb.studio.framework.editor.TextEditor.access$TextLine-AGcomas(TextEditor.kt:95)
	at com.vaticle.typedb.studio.framework.editor.TextEditor$TextLine$2.invoke(TextEditor.kt)
	at com.vaticle.typedb.studio.framework.editor.TextEditor$TextLine$2.invoke(TextEditor.kt)
	at androidx.compose.runtime.RecomposeScopeImpl.compose(RecomposeScopeImpl.kt:140)
	at androidx.compose.runtime.ComposerImpl.recomposeToGroupEnd(Composer.kt:2158)
	at androidx.compose.runtime.ComposerImpl.skipCurrentGroup(Composer.kt:2404)
	at androidx.compose.runtime.ComposerImpl$doCompose$2$5.invoke(Composer.kt:2585)
	at androidx.compose.runtime.ComposerImpl$doCompose$2$5.invoke(Composer.kt:2571)
	at androidx.compose.runtime.SnapshotStateKt__DerivedStateKt.observeDerivedStateRecalculations(DerivedState.kt:247)
	at androidx.compose.runtime.SnapshotStateKt.observeDerivedStateRecalculations(Unknown Source)
	at androidx.compose.runtime.ComposerImpl.doCompose(Composer.kt:2571)
	at androidx.compose.runtime.ComposerImpl.recompose$runtime(Composer.kt:2547)
	at androidx.compose.runtime.CompositionImpl.recompose(Composition.kt:620)
	at androidx.compose.runtime.Recomposer.performRecompose(Recomposer.kt:786)
	at androidx.compose.runtime.Recomposer.access$performRecompose(Recomposer.kt:105)
	at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$2.invoke(Recomposer.kt:456)
	at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$2.invoke(Recomposer.kt:425)
	at androidx.compose.runtime.BroadcastFrameClock$FrameAwaiter.resume(BroadcastFrameClock.kt:42)
	at androidx.compose.runtime.BroadcastFrameClock.sendFrame(BroadcastFrameClock.kt:71)
	at androidx.compose.ui.ComposeScene.render(ComposeScene.skiko.kt:351)
	at androidx.compose.ui.awt.ComposeLayer$1$onRender$1.invoke(ComposeLayer.desktop.kt:229)
	at androidx.compose.ui.awt.ComposeLayer$1$onRender$1.invoke(ComposeLayer.desktop.kt:227)
	at androidx.compose.ui.awt.ComposeLayer.catchExceptions(ComposeLayer.desktop.kt:89)
	at androidx.compose.ui.awt.ComposeLayer.access$catchExceptions(ComposeLayer.desktop.kt:70)
	at androidx.compose.ui.awt.ComposeLayer$1.onRender(ComposeLayer.desktop.kt:227)
	at org.jetbrains.skiko.SkiaLayer.update$skiko(SkiaLayer.awt.kt:438)
	at org.jetbrains.skiko.redrawer.MetalRedrawer.update(MetalRedrawer.kt:66)
	at org.jetbrains.skiko.redrawer.MetalRedrawer.access$update(MetalRedrawer.kt:13)
	at org.jetbrains.skiko.redrawer.MetalRedrawer$frameDispatcher$1.invokeSuspend(MetalRedrawer.kt:38)
	at org.jetbrains.skiko.redrawer.MetalRedrawer$frameDispatcher$1.invoke(MetalRedrawer.kt)
	at org.jetbrains.skiko.redrawer.MetalRedrawer$frameDispatcher$1.invoke(MetalRedrawer.kt)
	at org.jetbrains.skiko.FrameDispatcher$job$1.invokeSuspend(FrameDispatcher.kt:33)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)
```

**Comment by haikalpribadi** [comment]
This should now be fixed by https://github.com/vaticle/typedb-studio/commit/02fc948d233b1beda59764ae5a7496d696e822cc and should come out with the next release of Studio, happening today. Thanks for submitting the issue @izmalk!
