### ISSUE TITLE
Self-referential role and ray tracing

### ISSUE THREAD

**Issue by LeData** [vaticle/typedb-studio#675]
## Description

There is no error when defining a relation playing a single role in itself. But rendering will fail.

## Environment

1. TypeDB version: TypeDB 2.13.0
2. OS of TypeDB server: Windows 10 or Ubuntu 16.4
3. Studio version: TypeDB 2.11.0 (though it doesn't seem to be indicated anywhere in TypeDB Studio)
4. OS of Studio: Windows 10
5. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:

1. Commit a write schema transaction
```TypeQL
define

  A sub entity,
    plays R:source;
  B sub entity,
    plays R:target;

  R sub relation,
    relates source,
    relates target,
    relates parent,
    plays R:parent;
 ```
2. Run a read schema transaction
""" TypeQL
match $x sub thing;
"""
3. Move things around until it crashes
4. See the Error message:
``` 
arcThroughPoints: rayIntersect unexpectedly returned null! The arguments were Ray(origin=Offset(20.8, 75.6), directionVector=Offset(0.0, 0.0)), Ray(origin=Offset(20.8, 75.6), directionVector=Offset(0.0, 0.0))
```

## Expected Output

I'd expect either an error at commit time or a more helpful error message.

## Actual Output
The error message above.

## Additional information
If instead the schema is:
```
  R sub relation,
    relates source,
    relates target,
    relates parent,
    relates child,
    plays R:parent,
    plays R:child;
```
the application does not crash.

**Comment by LeData** [comment]
@jamesreprise I picked the name parent for a purpose. Suppose you have a hierarchical taxonomy of relations of one type. Then that hierarchy is a nested list, which as a model is a link from a thing to itself.

**Comment by gitvge** [comment]
I created a simplified version of which I think is the same issue. I am using this modelling approach quite often and believe it was working in the past. Hence I would appreciate if this could be fixed in due time. Thx.

schema commitement works fine:

`define
name sub attribute, value string;
collective sub relation, owns name, relates member, plays collective:member;
person sub entity, owns name,  plays collective:member;`

After some time and panning around the schema graph, studio crashes with the following error:
Title: arcThroughPoints: rayIntersect unexpectedly returned null! The arguments were Ray(origin=Offset(80.6, -24.5), directionVector=Offset(0.0, 0.0)), Ray(origin=Offset(80.6, -24.5), directionVector=Offset(0.0, 0.0))
Trace: java.lang.IllegalStateException: arcThroughPoints: rayIntersect unexpectedly returned null! The arguments were Ray(origin=Offset(80.6, -24.5), directionVector=Offset(0.0, 0.0)), Ray(origin=Offset(80.6, -24.5), directionVector=Offset(0.0, 0.0))
	at com.vaticle.typedb.studio.framework.common.geometry.Geometry.arcThroughPoints-r6Wi-ys(Geometry.kt:389)
	at com.vaticle.typedb.studio.framework.graph.EdgeRenderer.drawCurvedEdge-4WTKRHQ(EdgeRenderer.kt:68)
	at com.vaticle.typedb.studio.framework.graph.EdgeRenderer.draw-mxwnekA(EdgeRenderer.kt:55)
	at com.vaticle.typedb.studio.framework.graph.EdgeRenderer.draw(EdgeRenderer.kt:47)
	at com.vaticle.typedb.studio.framework.graph.GraphArea.drawEdges(GraphArea.kt:142)
	at com.vaticle.typedb.studio.framework.graph.GraphArea.access$drawEdges(GraphArea.kt:56)
	at com.vaticle.typedb.studio.framework.graph.GraphArea$Graphics$3.invoke(GraphArea.kt:107)
	at com.vaticle.typedb.studio.framework.graph.GraphArea$Graphics$3.invoke(GraphArea.kt:106)
	at androidx.compose.ui.draw.DrawBackgroundModifier.draw(DrawModifier.kt:104)
	at androidx.compose.ui.node.DrawEntity.draw(DrawEntity.kt:98)
	at androidx.compose.ui.node.LayoutNodeWrapper.drawContainedDrawModifiers(LayoutNodeWrapper.kt:320)
	at androidx.compose.ui.node.LayoutNodeWrapper.access$drawContainedDrawModifiers(LayoutNodeWrapper.kt:60)
	at androidx.compose.ui.node.LayoutNodeWrapper$invoke$1.invoke(LayoutNodeWrapper.kt:340)
	at androidx.compose.ui.node.LayoutNodeWrapper$invoke$1.invoke(LayoutNodeWrapper.kt:339)
	at androidx.compose.runtime.snapshots.Snapshot$Companion.observe(Snapshot.kt:2117)
	at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(SnapshotStateObserver.kt:113)
	at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui(OwnerSnapshotObserver.kt:78)
	at androidx.compose.ui.node.LayoutNodeWrapper.invoke(LayoutNodeWrapper.kt:339)
	at androidx.compose.ui.node.LayoutNodeWrapper$invokeOnCanvasInstance$1.invoke(LayoutNodeWrapper.kt:161)
	at androidx.compose.ui.node.LayoutNodeWrapper$invokeOnCanvasInstance$1.invoke(LayoutNodeWrapper.kt:161)
	at androidx.compose.ui.platform.SkiaLayer.performDrawLayer(SkiaLayer.skiko.kt:264)
	at androidx.compose.ui.platform.SkiaLayer.drawLayer(SkiaLayer.skiko.kt:225)
	at androidx.compose.ui.node.LayoutNodeWrapper.draw(LayoutNodeWrapper.kt:305)
	at androidx.compose.ui.node.ModifiedLayoutNode.performDraw(ModifiedLayoutNode.kt:139)
	at androidx.compose.ui.node.LayoutNodeWrapper.drawContainedDrawModifiers(LayoutNodeWrapper.kt:318)
	at androidx.compose.ui.node.LayoutNodeWrapper.draw(LayoutNodeWrapper.kt:310)
	at androidx.compose.ui.node.ModifiedLayoutNode.performDraw(ModifiedLayoutNode.kt:139)
	at androidx.compose.ui.node.LayoutNodeWrapper.drawContainedDrawModifiers(LayoutNodeWrapper.kt:318)
	at androidx.compose.ui.node.LayoutNodeWrapper.draw(LayoutNodeWrapper.kt:310)
	at androidx.compose.ui.node.LayoutNode.draw$ui(LayoutNode.kt:839)
	at androidx.compose.ui.node.InnerPlaceable.performDraw(InnerPlaceable.kt:90)
	at androidx.compose.ui.node.LayoutNodeDrawScope.drawContent(LayoutNodeDrawScope.kt:48)
	at androidx.compose.foundation.Background.draw(Background.kt:107)
	at androidx.compose.ui.node.DrawEntity.draw(DrawEntity.kt:98)
	at androidx.compose.ui.node.LayoutNodeWrapper.drawContainedDrawModifiers(LayoutNodeWrapper.kt:320)
	at androidx.compose.ui.node.LayoutNodeWrapper.access$drawContainedDrawModifiers(LayoutNodeWrapper.kt:60)
	at androidx.compose.ui.node.LayoutNodeWrapper$invoke$1.invoke(LayoutNodeWrapper.kt:340)
	at androidx.compose.ui.node.LayoutNodeWrapper$invoke$1.invoke(LayoutNodeWrapper.kt:339)
	at androidx.compose.runtime.snapshots.Snapshot$Companion.observe(Snapshot.kt:2117)
	at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(SnapshotStateObserver.kt:113)
	at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui(OwnerSnapshotObserver.kt:78)
	at androidx.compose.ui.node.LayoutNodeWrapper.invoke(LayoutNodeWrapper.kt:339)
	at androidx.compose.ui.node.LayoutNodeWrapper$invokeOnCanvasInstance$1.invoke(LayoutNodeWrapper.kt:161)
	at androidx.compose.ui.node.LayoutNodeWrapper$invokeOnCanvasInstance$1.invoke(LayoutNodeWrapper.kt:161)
	at androidx.compose.ui.platform.SkiaLayer.performDrawLayer(SkiaLayer.skiko.kt:264)
	at androidx.compose.ui.platform.SkiaLayer.drawLayer(SkiaLayer.skiko.kt:225)
	at androidx.compose.ui.node.LayoutNodeWrapper.draw(LayoutNodeWrapper.kt:305)
	at androidx.compose.ui.node.ModifiedLayoutNode.performDraw(ModifiedLayoutNode.kt:139)
	at androidx.compose.ui.node.LayoutNodeWrapper.drawContainedDrawModifiers(LayoutNodeWrapper.kt:318)
	at androidx.compose.ui.node.LayoutNodeWrapper.draw(LayoutNodeWrapper.kt:310)
	at androidx.compose.ui.node.LayoutNode.draw$ui(LayoutNode.kt:839)
	at androidx.compose.ui.node.InnerPlaceable.performDraw(InnerPlaceable.kt:90)
	at androidx.compose.ui.node.LayoutNodeWrapper.drawContainedDrawModifiers(LayoutNodeWrapper.kt:318)
	at androidx.compose.ui.node.LayoutNodeWrapper.draw(LayoutNodeWrapper.kt:310)
	at androidx.compose.ui.node.ModifiedLayoutNode.performDraw(ModifiedLayoutNode.kt:139)
	at androidx.compose.ui.node.LayoutNodeWrapper.drawContainedDrawModifiers(LayoutNodeWrapper.kt:318)
	at androidx.compose.ui.node.LayoutNodeWrapper.draw(LayoutNodeWrapper.kt:310)
	at androidx.compose.ui.node.ModifiedLayoutNode.performDraw(ModifiedLayoutNode.kt:139)
	at androidx.compose.ui.node.LayoutNodeWrapper.drawContainedDrawModifiers(LayoutNodeWrapper.kt:318)
	at androidx.compose.ui.node.LayoutNodeWrapper.draw(LayoutNodeWrapper.kt:310)
	at androidx.compose.ui.node.LayoutNode.draw$ui(LayoutNode.kt:839)
	at androidx.compose.ui.node.InnerPlaceable.performDraw(InnerPlaceable.kt:90)
	at androidx.compose.ui.node.LayoutNodeWrapper.drawContainedDrawModifiers(LayoutNodeWrapper.kt:318)
	at androidx.compose.ui.node.LayoutNodeWrapper.draw(LayoutNodeWrapper.kt:310)
	at androidx.compose.ui.node.ModifiedLayoutNode.performDraw(ModifiedLayoutNode.kt:139)
	at androidx.compose.ui.node.LayoutNodeWrapper.drawContainedDrawModifiers(LayoutNodeWrapper.kt:318)
	at androidx.compose.ui.node.LayoutNodeWrapper.draw(LayoutNodeWrapper.kt:310)
	at androidx.compose.ui.node.LayoutNode.draw$ui(LayoutNode.kt:839)
	at androidx.compose.ui.node.InnerPlaceable.performDraw(InnerPlaceable.kt:90)
	at androidx.compose.ui.node.LayoutNodeDrawScope.drawContent(LayoutNodeDrawScope.kt:48)
	at androidx.compose.foundation.Background.draw(Background.kt:107)
	at androidx.compose.ui.node.DrawEntity.draw(DrawEntity.kt:98)
	at androidx.compose.ui.node.LayoutNodeWrapper.drawContainedDrawModifiers(LayoutNodeWrapper.kt:320)
	at androidx.compose.ui.node.LayoutNodeWrapper.draw(LayoutNodeWrapper.kt:310)
	at androidx.compose.ui.node.ModifiedLayoutNode.performDraw(ModifiedLayoutNode.kt:139)
	at androidx.compose.ui.node.LayoutNodeWrapper.drawContainedDrawModifiers(LayoutNodeWrapper.kt:318)
	at androidx.compose.ui.node.LayoutNodeWrapper.draw(LayoutNodeWrapper.kt:310)
	at androidx.compose.ui.node.LayoutNode.draw$ui(LayoutNode.kt:839)
	at androidx.compose.ui.node.InnerPlaceable.performDraw(InnerPlaceable.kt:90)
	at androidx.compose.ui.node.LayoutNodeWrapper.drawContainedDrawModifiers(LayoutNodeWrapper.kt:318)
	at androidx.compose.ui.node.LayoutNodeWrapper.draw(LayoutNodeWrapper.kt:310)
	at androidx.compose.ui.node.LayoutNode.draw$ui(LayoutNode.kt:839)
	at androidx.compose.ui.node.InnerPlaceable.performDraw(InnerPlaceable.kt:90)
	at androidx.compose.ui.node.LayoutNodeWrapper.drawContainedDrawModifiers(LayoutNodeWrapper.kt:318)
	at androidx.compose.ui.node.LayoutNodeWrapper.draw(LayoutNodeWrapper.kt:310)
	at androidx.compose.ui.node.ModifiedLayoutNode.performDraw(ModifiedLayoutNode.kt:139)
	at androidx.compose.ui.node.LayoutNodeWrapper.drawContainedDrawModifiers(LayoutNodeWrapper.kt:318)
	at androidx.compose.ui.node.LayoutNodeWrapper.draw(LayoutNodeWrapper.kt:310)
	at androidx.compose.ui.node.LayoutNode.draw$ui(LayoutNode.kt:839)
	at androidx.compose.ui.node.InnerPlaceable.performDraw(InnerPlaceable.kt:90)
	at androidx.compose.ui.node.LayoutNodeWrapper.drawContainedDrawModifiers(LayoutNodeWrapper.kt:318)
	at androidx.compose.ui.node.LayoutNodeWrapper.draw(LayoutNodeWrapper.kt:310)
	at androidx.compose.ui.node.ModifiedLayoutNode.performDraw(ModifiedLayoutNode.kt:139)
	at androidx.compose.ui.node.LayoutNodeWrapper.drawContainedDrawModifiers(LayoutNodeWrapper.kt:318)
	at androidx.compose.ui.node.LayoutNodeWrapper.draw(LayoutNodeWrapper.kt:310)
	at androidx.compose.ui.node.LayoutNode.draw$ui(LayoutNode.kt:839)
	at androidx.compose.ui.node.InnerPlaceable.performDraw(InnerPlaceable.kt:90)
	at androidx.compose.ui.node.LayoutNodeWrapper.drawContainedDrawModifiers(LayoutNodeWrapper.kt:318)
	at androidx.compose.ui.node.LayoutNodeWrapper.draw(LayoutNodeWrapper.kt:310)
	at androidx.compose.ui.node.ModifiedLayoutNode.performDraw(ModifiedLayoutNode.kt:139)
	at androidx.compose.ui.node.LayoutNodeWrapper.drawContainedDrawModifiers(LayoutNodeWrapper.kt:318)
	at androidx.compose.ui.node.LayoutNodeWrapper.draw(LayoutNodeWrapper.kt:310)
	at androidx.compose.ui.node.LayoutNode.draw$ui(LayoutNode.kt:839)
	at androidx.compose.ui.node.InnerPlaceable.performDraw(InnerPlaceable.kt:90)
	at androidx.compose.ui.node.LayoutNodeWrapper.drawContainedDrawModifiers(LayoutNodeWrapper.kt:318)
	at androidx.compose.ui.node.LayoutNodeWrapper.draw(LayoutNodeWrapper.kt:310)
	at androidx.compose.ui.node.ModifiedLayoutNode.performDraw(ModifiedLayoutNode.kt:139)
	at androidx.compose.ui.node.LayoutNodeWrapper.drawContainedDrawModifiers(LayoutNodeWrapper.kt:318)
	at androidx.compose.ui.node.LayoutNodeWrapper.draw(LayoutNodeWrapper.kt:310)
	at androidx.compose.ui.node.ModifiedLayoutNode.performDraw(ModifiedLayoutNode.kt:139)
	at androidx.compose.ui.node.LayoutNodeWrapper.drawContainedDrawModifiers(LayoutNodeWrapper.kt:318)
	at androidx.compose.ui.node.LayoutNodeWrapper.draw(LayoutNodeWrapper.kt:310)
	at androidx.compose.ui.node.LayoutNode.draw$ui(LayoutNode.kt:839)
	at androidx.compose.ui.node.InnerPlaceable.performDraw(InnerPlaceable.kt:90)
	at androidx.compose.ui.node.LayoutNodeWrapper.drawContainedDrawModifiers(LayoutNodeWrapper.kt:318)
	at androidx.compose.ui.node.LayoutNodeWrapper.draw(LayoutNodeWrapper.kt:310)
	at androidx.compose.ui.node.ModifiedLayoutNode.performDraw(ModifiedLayoutNode.kt:139)
	at androidx.compose.ui.node.LayoutNodeWrapper.drawContainedDrawModifiers(LayoutNodeWrapper.kt:318)
	at androidx.compose.ui.node.LayoutNodeWrapper.draw(LayoutNodeWrapper.kt:310)
	at androidx.compose.ui.node.LayoutNode.draw$ui(LayoutNode.kt:839)
	at androidx.compose.ui.node.InnerPlaceable.performDraw(InnerPlaceable.kt:90)
	at androidx.compose.ui.node.LayoutNodeWrapper.drawContainedDrawModifiers(LayoutNodeWrapper.kt:318)
	at androidx.compose.ui.node.LayoutNodeWrapper.draw(LayoutNodeWrapper.kt:310)
	at androidx.compose.ui.node.ModifiedLayoutNode.performDraw(ModifiedLayoutNode.kt:139)
	at androidx.compose.ui.node.LayoutNodeWrapper.drawContainedDrawModifiers(LayoutNodeWrapper.kt:318)
	at androidx.compose.ui.node.LayoutNodeWrapper.draw(LayoutNodeWrapper.kt:310)
	at androidx.compose.ui.node.LayoutNode.draw$ui(LayoutNode.kt:839)
	at androidx.compose.ui.node.InnerPlaceable.performDraw(InnerPlaceable.kt:90)
	at androidx.compose.ui.node.LayoutNodeWrapper.drawContainedDrawModifiers(LayoutNodeWrapper.kt:318)
	at androidx.compose.ui.node.LayoutNodeWrapper.draw(LayoutNodeWrapper.kt:310)
	at androidx.compose.ui.node.ModifiedLayoutNode.performDraw(ModifiedLayoutNode.kt:139)
	at androidx.compose.ui.node.LayoutNodeWrapper.drawContainedDrawModifiers(LayoutNodeWrapper.kt:318)
	at androidx.compose.ui.node.LayoutNodeWrapper.draw(LayoutNodeWrapper.kt:310)
	at androidx.compose.ui.node.LayoutNode.draw$ui(LayoutNode.kt:839)
	at androidx.compose.ui.node.InnerPlaceable.performDraw(InnerPlaceable.kt:90)
	at androidx.compose.ui.node.LayoutNodeWrapper.drawContainedDrawModifiers(LayoutNodeWrapper.kt:318)
	at androidx.compose.ui.node.LayoutNodeWrapper.draw(LayoutNodeWrapper.kt:310)
	at androidx.compose.ui.node.ModifiedLayoutNode.performDraw(ModifiedLayoutNode.kt:139)
	at androidx.compose.ui.node.LayoutNodeWrapper.drawContainedDrawModifiers(LayoutNodeWrapper.kt:318)
	at androidx.compose.ui.node.LayoutNodeWrapper.draw(LayoutNodeWrapper.kt:310)
	at androidx.compose.ui.node.ModifiedLayoutNode.performDraw(ModifiedLayoutNode.kt:139)
	at androidx.compose.ui.node.LayoutNodeWrapper.drawContainedDrawModifiers(LayoutNodeWrapper.kt:318)
	at androidx.compose.ui.node.LayoutNodeWrapper.draw(LayoutNodeWrapper.kt:310)
	at androidx.compose.ui.node.LayoutNode.draw$ui(LayoutNode.kt:839)
	at androidx.compose.ui.node.InnerPlaceable.performDraw(InnerPlaceable.kt:90)
	at androidx.compose.ui.node.LayoutNodeWrapper.drawContainedDrawModifiers(LayoutNodeWrapper.kt:318)
	at androidx.compose.ui.node.LayoutNodeWrapper.draw(LayoutNodeWrapper.kt:310)
	at androidx.compose.ui.node.ModifiedLayoutNode.performDraw(ModifiedLayoutNode.kt:139)
	at androidx.compose.ui.node.LayoutNodeWrapper.drawContainedDrawModifiers(LayoutNodeWrapper.kt:318)
	at androidx.compose.ui.node.LayoutNodeWrapper.draw(LayoutNodeWrapper.kt:310)
	at androidx.compose.ui.node.LayoutNode.draw$ui(LayoutNode.kt:839)
	at androidx.compose.ui.node.InnerPlaceable.performDraw(InnerPlaceable.kt:90)
	at androidx.compose.ui.node.LayoutNodeWrapper.drawContainedDrawModifiers(LayoutNodeWrapper.kt:318)
	at androidx.compose.ui.node.LayoutNodeWrapper.draw(LayoutNodeWrapper.kt:310)
	at androidx.compose.ui.node.ModifiedLayoutNode.performDraw(ModifiedLayoutNode.kt:139)
	at androidx.compose.ui.node.LayoutNodeWrapper.drawContainedDrawModifiers(LayoutNodeWrapper.kt:318)
	at androidx.compose.ui.node.LayoutNodeWrapper.draw(LayoutNodeWrapper.kt:310)
	at androidx.compose.ui.node.LayoutNode.draw$ui(LayoutNode.kt:839)
	at androidx.compose.ui.node.InnerPlaceable.performDraw(InnerPlaceable.kt:90)
	at androidx.compose.ui.node.LayoutNodeDrawScope.drawContent(LayoutNodeDrawScope.kt:48)
	at androidx.compose.foundation.Background.draw(Background.kt:107)
	at androidx.compose.ui.node.DrawEntity.draw(DrawEntity.kt:98)
	at androidx.compose.ui.node.LayoutNodeWrapper.drawContainedDrawModifiers(LayoutNodeWrapper.kt:320)
	at androidx.compose.ui.node.LayoutNodeWrapper.draw(LayoutNodeWrapper.kt:310)
	at androidx.compose.ui.node.ModifiedLayoutNode.performDraw(ModifiedLayoutNode.kt:139)
	at androidx.compose.ui.node.LayoutNodeWrapper.drawContainedDrawModifiers(LayoutNodeWrapper.kt:318)
	at androidx.compose.ui.node.LayoutNodeWrapper.access$drawContainedDrawModifiers(LayoutNodeWrapper.kt:60)
	at androidx.compose.ui.node.LayoutNodeWrapper$invoke$1.invoke(LayoutNodeWrapper.kt:340)
	at androidx.compose.ui.node.LayoutNodeWrapper$invoke$1.invoke(LayoutNodeWrapper.kt:339)
	at androidx.compose.runtime.snapshots.Snapshot$Companion.observe(Snapshot.kt:2117)
	at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(SnapshotStateObserver.kt:113)
	at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui(OwnerSnapshotObserver.kt:78)
	at androidx.compose.ui.node.LayoutNodeWrapper.invoke(LayoutNodeWrapper.kt:339)
	at androidx.compose.ui.node.LayoutNodeWrapper$invokeOnCanvasInstance$1.invoke(LayoutNodeWrapper.kt:161)
	at androidx.compose.ui.node.LayoutNodeWrapper$invokeOnCanvasInstance$1.invoke(LayoutNodeWrapper.kt:161)
	at androidx.compose.ui.platform.SkiaLayer.performDrawLayer(SkiaLayer.skiko.kt:264)
	at androidx.compose.ui.platform.SkiaLayer.drawLayer(SkiaLayer.skiko.kt:225)
	at androidx.compose.ui.node.LayoutNodeWrapper.draw(LayoutNodeWrapper.kt:305)
	at androidx.compose.ui.node.LayoutNode.draw$ui(LayoutNode.kt:839)
	at androidx.compose.ui.node.InnerPlaceable.performDraw(InnerPlaceable.kt:90)
	at androidx.compose.ui.node.LayoutNodeWrapper.drawContainedDrawModifiers(LayoutNodeWrapper.kt:318)
	at androidx.compose.ui.node.LayoutNodeWrapper.draw(LayoutNodeWrapper.kt:310)
	at androidx.compose.ui.node.LayoutNode.draw$ui(LayoutNode.kt:839)
	at androidx.compose.ui.platform.SkiaBasedOwner.draw(SkiaBasedOwner.skiko.kt:346)
	at androidx.compose.ui.ComposeScene.render(ComposeScene.skiko.kt:419)
	at androidx.compose.ui.awt.ComposeLayer$1$onRender$1.invoke(ComposeLayer.desktop.kt:326)
	at androidx.compose.ui.awt.ComposeLayer$1$onRender$1.invoke(ComposeLayer.desktop.kt:325)
	at androidx.compose.ui.awt.ComposeLayer.catchExceptions(ComposeLayer.desktop.kt:109)
	at androidx.compose.ui.awt.ComposeLayer.access$catchExceptions(ComposeLayer.desktop.kt:87)
	at androidx.compose.ui.awt.ComposeLayer$1.onRender(ComposeLayer.desktop.kt:325)
	at org.jetbrains.skiko.SkiaLayer.update$skiko(SkiaLayer.awt.kt:510)
	at org.jetbrains.skiko.redrawer.AWTRedrawer.update(AWTRedrawer.kt:54)
	at org.jetbrains.skiko.redrawer.Direct3DRedrawer$frameDispatcher$1.invokeSuspend(Direct3DRedrawer.kt:40)
	at org.jetbrains.skiko.redrawer.Direct3DRedrawer$frameDispatcher$1.invoke(Direct3DRedrawer.kt)
	at org.jetbrains.skiko.redrawer.Direct3DRedrawer$frameDispatcher$1.invoke(Direct3DRedrawer.kt)
	at org.jetbrains.skiko.FrameDispatcher$job$1.invokeSuspend(FrameDispatcher.kt:33)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)

**Comment by alexjpwalker** [comment]
This should no longer happen in Studio 3 due to no longer using custom rendering logic.
