### ISSUE TITLE
vaticle, does not exist

### ISSUE THREAD

**Issue by Constantina564** [vaticle/typedb-studio#680]
TypeDB version: TypeDB 2.8.0

1. cmd typedb server
2. cmd typedb console
3. > transaction le schema write
le::schema::write> source C:\\Users\\ntina\\Downloads\\typedb-all-windows-2.8.0\\le.tql
Concepts have been defined
Concepts have been defined
[TYR03] Invalid Type Read: The type 'question-Has-answer' does not exist.

Please check server logs for the stack trace.

22:15:34.009 [typedb-service::0] ERROR com.vaticle.typedb.core.server.TransactionService - [TYR03] Invalid Type Read: The type 'question-Has-answer' does not exist.
com.vaticle.typedb.core.common.exception.TypeDBException: [TYR03] Invalid Type Read: The type 'question-Has-answer' does not exist.
        at com.vaticle.typedb.core.common.exception.TypeDBException.of(TypeDBException.java:55)
        at com.vaticle.typedb.core.query.Definer.define(Definer.java:118)
        at com.vaticle.typedb.core.query.Definer.lambda$definePlays$4(Definer.java:251)
        at java.base/java.lang.Iterable.forEach(Iterable.java:75)
        at com.vaticle.typedb.core.query.Definer.definePlays(Definer.java:250)
        at com.vaticle.typedb.core.query.Definer.define(Definer.java:132)
        at com.vaticle.typedb.core.query.Definer.lambda$execute$0(Definer.java:93)
        at java.base/java.lang.Iterable.forEach(Iterable.java:75)
        at java.base/java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1092)
        at com.vaticle.typedb.core.query.Definer.execute(Definer.java:92)
        at com.vaticle.typedb.core.query.QueryManager.define(QueryManager.java:168)
        at com.vaticle.typedb.core.server.query.QueryService.define(QueryService.java:117)
        at com.vaticle.typedb.core.server.query.QueryService.execute(QueryService.java:78)
        at com.vaticle.typedb.core.server.TransactionService.executeRequest(TransactionService.java:170)
        at com.vaticle.typedb.core.server.TransactionService.execute(TransactionService.java:146)
        at com.vaticle.typedb.core.server.TransactionService.onNext(TransactionService.java:122)
        at com.vaticle.typedb.core.server.TransactionService.onNext(TransactionService.java:79)
        at io.grpc.stub.ServerCalls$StreamingServerCallHandler$StreamingServerCallListener.onMessage(ServerCalls.java:262)
        at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.messagesAvailableInternal(ServerCallImpl.java:318)
        at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.messagesAvailable(ServerCallImpl.java:301)
        at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1MessagesAvailable.runInContext(ServerImpl.java:834)
        at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
        at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by Constantina564** [comment]
The entities and attributes are displayed correctly.
But when I add the relationships between them it keeps showing me this.

**Comment by alexjpwalker** [comment]
Could you share your `.tql` file (anonymised if necessary) or a minimal subset of it that reproduces the problem, @Constantina564 ?
